/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated/ops'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedOpsIndexRouteImport } from './routes/_authenticated/ops.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedOpsQuotationsRouteImport } from './routes/_authenticated/ops.quotations'
import { Route as AuthenticatedOpsProductsRouteImport } from './routes/_authenticated/ops.products'
import { Route as AuthenticatedOpsOrdersRouteImport } from './routes/_authenticated/ops.orders'
import { Route as AuthenticatedOpsLiveRouteImport } from './routes/_authenticated/ops.live'
import { Route as AuthenticatedOpsInventoryRouteImport } from './routes/_authenticated/ops.inventory'
import { Route as AuthenticatedOpsCustomersRouteImport } from './routes/_authenticated/ops.customers'
import { Route as AuthenticatedOpsAccountsRouteImport } from './routes/_authenticated/ops.accounts'
import { Route as AuthenticatedAccountWishlistRouteImport } from './routes/_authenticated/account.wishlist'
import { Route as AuthenticatedAccountOrdersRouteImport } from './routes/_authenticated/account.orders'
import { Route as AuthenticatedAccountBusinessRouteImport } from './routes/_authenticated/account.business'
import { Route as AuthenticatedAccountAddressesRouteImport } from './routes/_authenticated/account.addresses'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CollectionsRoute,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpsIndexRoute = AuthenticatedOpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOpsRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedOpsQuotationsRoute =
  AuthenticatedOpsQuotationsRouteImport.update({
    id: '/quotations',
    path: '/quotations',
    getParentRoute: () => AuthenticatedOpsRoute,
  } as any)
const AuthenticatedOpsProductsRoute =
  AuthenticatedOpsProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedOpsRoute,
  } as any)
const AuthenticatedOpsOrdersRoute = AuthenticatedOpsOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedOpsRoute,
} as any)
const AuthenticatedOpsLiveRoute = AuthenticatedOpsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AuthenticatedOpsRoute,
} as any)
const AuthenticatedOpsInventoryRoute =
  AuthenticatedOpsInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedOpsRoute,
  } as any)
const AuthenticatedOpsCustomersRoute =
  AuthenticatedOpsCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedOpsRoute,
  } as any)
const AuthenticatedOpsAccountsRoute =
  AuthenticatedOpsAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedOpsRoute,
  } as any)
const AuthenticatedAccountWishlistRoute =
  AuthenticatedAccountWishlistRouteImport.update({
    id: '/wishlist',
    path: '/wishlist',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountOrdersRoute =
  AuthenticatedAccountOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountBusinessRoute =
  AuthenticatedAccountBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedAccountAddressesRoute =
  AuthenticatedAccountAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/ops': typeof AuthenticatedOpsRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/business': typeof AuthenticatedAccountBusinessRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/ops/accounts': typeof AuthenticatedOpsAccountsRoute
  '/ops/customers': typeof AuthenticatedOpsCustomersRoute
  '/ops/inventory': typeof AuthenticatedOpsInventoryRoute
  '/ops/live': typeof AuthenticatedOpsLiveRoute
  '/ops/orders': typeof AuthenticatedOpsOrdersRoute
  '/ops/products': typeof AuthenticatedOpsProductsRoute
  '/ops/quotations': typeof AuthenticatedOpsQuotationsRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/ops/': typeof AuthenticatedOpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products': typeof ProductsIndexRoute
  '/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/account/business': typeof AuthenticatedAccountBusinessRoute
  '/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/ops/accounts': typeof AuthenticatedOpsAccountsRoute
  '/ops/customers': typeof AuthenticatedOpsCustomersRoute
  '/ops/inventory': typeof AuthenticatedOpsInventoryRoute
  '/ops/live': typeof AuthenticatedOpsLiveRoute
  '/ops/orders': typeof AuthenticatedOpsOrdersRoute
  '/ops/products': typeof AuthenticatedOpsProductsRoute
  '/ops/quotations': typeof AuthenticatedOpsQuotationsRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/ops': typeof AuthenticatedOpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRouteWithChildren
  '/contact': typeof ContactRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/story': typeof StoryRoute
  '/trade': typeof TradeRoute
  '/wishlist': typeof WishlistRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/ops': typeof AuthenticatedOpsRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/account/addresses': typeof AuthenticatedAccountAddressesRoute
  '/_authenticated/account/business': typeof AuthenticatedAccountBusinessRoute
  '/_authenticated/account/orders': typeof AuthenticatedAccountOrdersRoute
  '/_authenticated/account/wishlist': typeof AuthenticatedAccountWishlistRoute
  '/_authenticated/ops/accounts': typeof AuthenticatedOpsAccountsRoute
  '/_authenticated/ops/customers': typeof AuthenticatedOpsCustomersRoute
  '/_authenticated/ops/inventory': typeof AuthenticatedOpsInventoryRoute
  '/_authenticated/ops/live': typeof AuthenticatedOpsLiveRoute
  '/_authenticated/ops/orders': typeof AuthenticatedOpsOrdersRoute
  '/_authenticated/ops/products': typeof AuthenticatedOpsProductsRoute
  '/_authenticated/ops/quotations': typeof AuthenticatedOpsQuotationsRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/ops/': typeof AuthenticatedOpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/craftsmanship'
    | '/sitemap.xml'
    | '/story'
    | '/trade'
    | '/wishlist'
    | '/account'
    | '/ops'
    | '/collections/$slug'
    | '/products/$slug'
    | '/products/'
    | '/account/addresses'
    | '/account/business'
    | '/account/orders'
    | '/account/wishlist'
    | '/ops/accounts'
    | '/ops/customers'
    | '/ops/inventory'
    | '/ops/live'
    | '/ops/orders'
    | '/ops/products'
    | '/ops/quotations'
    | '/account/'
    | '/ops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/craftsmanship'
    | '/sitemap.xml'
    | '/story'
    | '/trade'
    | '/wishlist'
    | '/collections/$slug'
    | '/products/$slug'
    | '/products'
    | '/account/addresses'
    | '/account/business'
    | '/account/orders'
    | '/account/wishlist'
    | '/ops/accounts'
    | '/ops/customers'
    | '/ops/inventory'
    | '/ops/live'
    | '/ops/orders'
    | '/ops/products'
    | '/ops/quotations'
    | '/account'
    | '/ops'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/craftsmanship'
    | '/sitemap.xml'
    | '/story'
    | '/trade'
    | '/wishlist'
    | '/_authenticated/account'
    | '/_authenticated/ops'
    | '/collections/$slug'
    | '/products/$slug'
    | '/products/'
    | '/_authenticated/account/addresses'
    | '/_authenticated/account/business'
    | '/_authenticated/account/orders'
    | '/_authenticated/account/wishlist'
    | '/_authenticated/ops/accounts'
    | '/_authenticated/ops/customers'
    | '/_authenticated/ops/inventory'
    | '/_authenticated/ops/live'
    | '/_authenticated/ops/orders'
    | '/_authenticated/ops/products'
    | '/_authenticated/ops/quotations'
    | '/_authenticated/account/'
    | '/_authenticated/ops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoryRoute: typeof StoryRoute
  TradeRoute: typeof TradeRoute
  WishlistRoute: typeof WishlistRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof CollectionsRoute
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ops/': {
      id: '/_authenticated/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof AuthenticatedOpsIndexRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/ops/quotations': {
      id: '/_authenticated/ops/quotations'
      path: '/quotations'
      fullPath: '/ops/quotations'
      preLoaderRoute: typeof AuthenticatedOpsQuotationsRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/ops/products': {
      id: '/_authenticated/ops/products'
      path: '/products'
      fullPath: '/ops/products'
      preLoaderRoute: typeof AuthenticatedOpsProductsRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/ops/orders': {
      id: '/_authenticated/ops/orders'
      path: '/orders'
      fullPath: '/ops/orders'
      preLoaderRoute: typeof AuthenticatedOpsOrdersRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/ops/live': {
      id: '/_authenticated/ops/live'
      path: '/live'
      fullPath: '/ops/live'
      preLoaderRoute: typeof AuthenticatedOpsLiveRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/ops/inventory': {
      id: '/_authenticated/ops/inventory'
      path: '/inventory'
      fullPath: '/ops/inventory'
      preLoaderRoute: typeof AuthenticatedOpsInventoryRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/ops/customers': {
      id: '/_authenticated/ops/customers'
      path: '/customers'
      fullPath: '/ops/customers'
      preLoaderRoute: typeof AuthenticatedOpsCustomersRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/ops/accounts': {
      id: '/_authenticated/ops/accounts'
      path: '/accounts'
      fullPath: '/ops/accounts'
      preLoaderRoute: typeof AuthenticatedOpsAccountsRouteImport
      parentRoute: typeof AuthenticatedOpsRoute
    }
    '/_authenticated/account/wishlist': {
      id: '/_authenticated/account/wishlist'
      path: '/wishlist'
      fullPath: '/account/wishlist'
      preLoaderRoute: typeof AuthenticatedAccountWishlistRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/orders': {
      id: '/_authenticated/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AuthenticatedAccountOrdersRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/business': {
      id: '/_authenticated/account/business'
      path: '/business'
      fullPath: '/account/business'
      preLoaderRoute: typeof AuthenticatedAccountBusinessRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/account/addresses': {
      id: '/_authenticated/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AuthenticatedAccountAddressesRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountAddressesRoute: typeof AuthenticatedAccountAddressesRoute
  AuthenticatedAccountBusinessRoute: typeof AuthenticatedAccountBusinessRoute
  AuthenticatedAccountOrdersRoute: typeof AuthenticatedAccountOrdersRoute
  AuthenticatedAccountWishlistRoute: typeof AuthenticatedAccountWishlistRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountAddressesRoute: AuthenticatedAccountAddressesRoute,
  AuthenticatedAccountBusinessRoute: AuthenticatedAccountBusinessRoute,
  AuthenticatedAccountOrdersRoute: AuthenticatedAccountOrdersRoute,
  AuthenticatedAccountWishlistRoute: AuthenticatedAccountWishlistRoute,
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedOpsRouteChildren {
  AuthenticatedOpsAccountsRoute: typeof AuthenticatedOpsAccountsRoute
  AuthenticatedOpsCustomersRoute: typeof AuthenticatedOpsCustomersRoute
  AuthenticatedOpsInventoryRoute: typeof AuthenticatedOpsInventoryRoute
  AuthenticatedOpsLiveRoute: typeof AuthenticatedOpsLiveRoute
  AuthenticatedOpsOrdersRoute: typeof AuthenticatedOpsOrdersRoute
  AuthenticatedOpsProductsRoute: typeof AuthenticatedOpsProductsRoute
  AuthenticatedOpsQuotationsRoute: typeof AuthenticatedOpsQuotationsRoute
  AuthenticatedOpsIndexRoute: typeof AuthenticatedOpsIndexRoute
}

const AuthenticatedOpsRouteChildren: AuthenticatedOpsRouteChildren = {
  AuthenticatedOpsAccountsRoute: AuthenticatedOpsAccountsRoute,
  AuthenticatedOpsCustomersRoute: AuthenticatedOpsCustomersRoute,
  AuthenticatedOpsInventoryRoute: AuthenticatedOpsInventoryRoute,
  AuthenticatedOpsLiveRoute: AuthenticatedOpsLiveRoute,
  AuthenticatedOpsOrdersRoute: AuthenticatedOpsOrdersRoute,
  AuthenticatedOpsProductsRoute: AuthenticatedOpsProductsRoute,
  AuthenticatedOpsQuotationsRoute: AuthenticatedOpsQuotationsRoute,
  AuthenticatedOpsIndexRoute: AuthenticatedOpsIndexRoute,
}

const AuthenticatedOpsRouteWithChildren =
  AuthenticatedOpsRoute._addFileChildren(AuthenticatedOpsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedOpsRoute: AuthenticatedOpsRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CollectionsRouteChildren {
  CollectionsSlugRoute: typeof CollectionsSlugRoute
}

const CollectionsRouteChildren: CollectionsRouteChildren = {
  CollectionsSlugRoute: CollectionsSlugRoute,
}

const CollectionsRouteWithChildren = CollectionsRoute._addFileChildren(
  CollectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRouteWithChildren,
  ContactRoute: ContactRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoryRoute: StoryRoute,
  TradeRoute: TradeRoute,
  WishlistRoute: WishlistRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
